=== JorudiSAMA/MarkupProject/xml/artist.dtd
<!ELEMENT artist (image1, info, description, image2)>
<!ELEMENT image1 (#PCDATA)>
<!ELEMENT info (name, born, age, genres, activity-period, related-artists, email)>
<!ATTLIST info
          category CDATA #IMPLIED
          id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
          full-name CDATA #REQUIRED>
<!ELEMENT born (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT genres (#PCDATA)>
<!ELEMENT activity-period (#PCDATA)>
<!ELEMENT related-artists (related-artist+)>
<!ATTLIST related-artists
          full-list CDATA #REQUIRED>
<!ELEMENT related-artist (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email
          active CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image2 (#PCDATA)>

=== JorudiSAMA/MarkupProject/xml/artist.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="artist.css"?>
<!-- Document creat per Jordi Casesnoves Martin-->
<!DOCTYPE artist SYSTEM "artist.dtd">
<artist>
    <image1></image1>
    <info category="rap" id="kendricklamar">
        <name full-name="true">Kendrick Lamar Duckworth</name>
        <born>June 17, 1987, Compton, LA, California, US</born>
        <age>30</age>
        <genres>Hip Hop</genres>
        <activity-period>2003 - Now</activity-period>
        <related-artists full-list="false">
            <related-artist>Black Hippy</related-artist>
            <related-artist>Dr. Dre</related-artist>
            <related-artist>J. Cole</related-artist>
            <related-artist>Ash Riser</related-artist>
        </related-artists>
        <email active="true"><![CDATA[kendricklamar@gmail.com]]></email>
    </info>
    <description></description>
    <image2></image2>
</artist>
